query getAllMiniApps($data: AllMiniAppsInput!) {
    allMiniApps: allMiniApps(
        data: $data,
    ) {
        id
        name
        shortDescription
        connected
        accessible
        category
        logo
        label
        icon
        menuCategory
    }
}

query getAllB2BApps ($where: B2BAppWhereInput, $first: Int, $skip: Int, $sortBy: [SortB2BAppsBy!]) {
    objs: allB2BApps (where: $where, first: $first, skip: $skip, sortBy: $sortBy) {
        id
        name
        shortDescription
        detailedDescription
        icon
        category
        label
        appUrl
        logo {
            publicUrl
        }
        developer
        developerUrl
        isHidden
        isGlobal
        isPublic
        displayPriority
        menuCategory
        createdAt
        updatedAt
    }
}